[slack.my-slack]
Token="${SLACK_TOKEN}"
AppToken="${SLACK_APP_TOKEN}"
UseSocketMode=true
UseRTM=false
RemoteNickFormat="{NICK} "

[discord.my-discord]
Token="${DISCORD_TOKEN}"
Server="${DISCORD_SERVER_ID}"
AutoWebhooks=true
RemoteNickFormat="{NICK} "
WebhookNameFormat="{NICK} "
WebhookAvatarFormat="{AVATARURL}"
# Gateway definitions are injected from channels.csv
##__GENERATED_GATEWAYS__##